### ISSUE TITLE
Possible security hole with sudo invocation

### ISSUE THREAD

**Issue by mutemule** [PingTrip/broctl-setcap#1]
I've been working on a Chef cookbook for Bro, and got stuck in a bit of a chicken-and-egg scenario with trying to use `incron` to set the appropriate capabilities on these files.  Your plugin is precisely what I needed; thanks!

However, I've used a slightly modified version, because there's a small window for a security hole in the configuration proposed:

The `bro` user is granted root-execution perms on `bro_setcap.sh`, with no password prompt.  As well, the `bro` user will likely have write-access to `bro_setcap.sh`, as the script is (almost certainly, but not necessarily) copied out as this same `bro` user.  It is theoretically plausible for someone to modify the script between the time it is written and the time it is run.

I'm looking at a somewhat less-clean approach right now of executing the two `setcap` commands directly by python (joined via `&&`), rather than executing a script that executes `setcap`.

**Comment by PingTrip** [comment]
That is a fair concern and I'll add an option for the user to choose the method of execution, either setcap directly or via a script. (having the script is convenient when you want to manually reset the capabilities on node).

In my cluster deployments I consider any unauthorized access to a Bro manager or node as catastrophic. If someone has access to the bro user that means they have full access to view all network traffic that I'm monitoring, Ouch. Separate admin network, 2F Auth, and local IPTable ACLs restricting communication from other than specific nodes/managers, etc are my defenses, if you've got shell I've already lost. However, I can see your concern if a Bro node is deployed in a "hostile" network and the additional damage that elevated privileges could have if the server were a member of domain, etc. I'll get the change pushed this weekend.

**Comment by PingTrip** [comment]
The plugin has been modified to call `setcap` directly to eliminate concerns with a threat actor modifying the shell script.
