### ISSUE TITLE
Privilege escalation with unlimited setcap is trivial

### ISSUE THREAD

**Issue by ryancmoon** [PingTrip/broctl-setcap#2]
You would be better off creating a script that sudo can call that takes a filename to perform the setcap attributes on as an argument that is passed to `/sbin/setcap cap_net_raw,cap_net_admin=eip $filename`. As this module is set up presently, the bro user can grant any script they like with CAP_CHOWN and CAP_DAC_OVERRIDE  and run anything as root.

**Comment by PingTrip** [comment]
Great observation Ryan, I'll get this change added in shortly.

**Comment by PingTrip** [comment]
Thanks again @ryancmoon. I updated the sudoers config to restrict the setcap call to the specific arguments required.
